set -g mouse on
set -g history-limit 10000
set -s escape-time 0

# splits
bind | split-window -h
bind - split-window -v

# reload
bind r source-file ~/.tmux.conf \; display "Reloaded"

# colors
set -g default-terminal "screen-256color"
